version: '3.8'  # Specify the version of Docker Compose

services:
  app:
    image: node-app-test-new:1.0.0-9
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      # You can specify environment variables here if needed
      NODE_ENV: production
    volumes:
      - ./:/node  # Optional: Mount the current directory to /node in the container

    # Optional: Add restart policy
    restart: unless-stopped  
