version: '3.8'

services:
  app:
    image: node-app-test-new:20241014-074402-3
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      NODE_ENV: production
    working_dir: /node  # Set the working directory in the container
    command: ["node", "app.js"]  # Specify the command to run your application
    restart: unless-stopped  # Restart policy

  backend:
    image: java-backend-image:2024-10-14-07-42-23-build-15:2024-10-14-07-42-23-build-15
    ports:
      - "9090:8080"  # Map host port 9090 to container port 8080
    environment:
      JAVA_ENV: production
    depends_on:
      - app  # Ensure backend starts after app
    restart: unless-stopped  # Restart policy
