# version: '3.8'

# services:
#   app:
#     image: node-app-test-new:2024-10-14-08-27-00-frontend-build-25
#     ports:
#       - "8000:8000"  # Map host port 8000 to container port 8000
#     environment:
#       NODE_ENV: production
#     working_dir: /node  # Set the working directory in the container
#     command: ["node", "app.js"]  # Specify the command to run your application
#     restart: unless-stopped  # Restart policy

#   backend:
#     image: java-backend-image:2024-10-14-08-32-59-build-18
#     ports:
#       - "9090:8080"  # Map host port 9090 to container port 8080
#     environment:
#       JAVA_ENV: production
#     depends_on:
#       - app  # Ensure backend starts after app
#     restart: unless-stopped  # Restart policy
version: '3.8'

services:
  app:
    image: node-app-test-new:2024-10-14-08-27-00-frontend-build-25
    ports:
      - "8000:80"  # Map host port 8000 to container port 8000
    environment:
      NODE_ENV: production
    working_dir: /node  # Set the working directory in the container
    command: ["node", "app.js"]  # Specify the command to run your application
    restart: unless-stopped  # Restart policy

  backend:
    image: java-backend-image:2024-10-14-08-29-17-build-17  # Removed duplicate tag
    ports:
      - "7072:7072"  # Map host port 9090 to container port 8080
    environment:
      JAVA_ENV: production
    depends_on:
      - app  # Ensure backend starts after app
    restart: unless-stopped  # Restart policy

networks:
  default:
    driver: bridge
