version: '3.8'  # Specify the version of Docker Compose

services:
  app:
    image: node-app-test-new:1.0.0-10
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      NODE_ENV: production  # Environment variables
    volumes:
      - ./:/node  # Optional: Mount the current directory to /node in the container
    restart: unless-stopped  # Restart policy

  backend:
    image: java-backend-image:1.0.0-17
    ports:
      - "9090:8080"  # Map host port 8080 to container port 8080
    environment:
      # Specify environment variables if needed
      JAVA_ENV: production
    volumes:
      - ./backend:/app  # Optional: Mount the backend directory to /app in the container
    depends_on:
      - app  # Ensure backend starts after app
    restart: unless-stopped  # Restart policy
